import Link from "next/link";

const content = {
  en: { title: "Documentation", intro: "Use BioSTAR for targeted sequence conversion and analysis.", request: "Request an API key", usage: "API usage", limits: "Limits", swagger: "Interactive Swagger API", guide: "API keys are issued by request. Email api@bioapps.org with your intended use and expected volume.", body: "Public requests are rate-limited. Use X-API-Key for authenticated programmatic access.", limitBody: "GET conversion requests accept up to 1,000 nucleotides. POST and batch analysis requests accept up to 10,000 characters per sequence." },
  pt: { title: "Documentação", intro: "Use o BioSTAR para conversão e análise direcionada de sequências.", request: "Solicitar chave de API", usage: "Uso da API", limits: "Limites", swagger: "Swagger interativo da API", guide: "As chaves de API são emitidas mediante solicitação. Envie um e-mail para api@bioapps.org informando o uso pretendido e o volume esperado.", body: "Requisições públicas possuem limite de frequência. Use X-API-Key para acesso programático autenticado.", limitBody: "As conversões GET aceitam até 1.000 nucleotídeos. As análises POST e batch aceitam até 10.000 caracteres por sequência." },
  es: { title: "Documentación", intro: "Usa BioSTAR para conversión y análisis dirigido de secuencias.", request: "Solicitar clave de API", usage: "Uso de la API", limits: "Límites", swagger: "Swagger interactivo de la API", guide: "Las claves de API se emiten bajo solicitud. Envía un correo a api@bioapps.org indicando el uso previsto y el volumen esperado.", body: "Las solicitudes públicas tienen límites de frecuencia. Usa X-API-Key para acceso programático autenticado.", limitBody: "Las conversiones GET aceptan hasta 1.000 nucleótidos. Los análisis POST y batch aceptan hasta 10.000 caracteres por secuencia." },
};

export default async function DocsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = content[locale as keyof typeof content] ?? content.en;
  return <main className="docs-page"><header><Link href={`/${locale}`}>BioSTAR</Link><span> / {t.title}</span></header><section className="docs-hero"><p className="eyebrow">BioSTAR API</p><h1>{t.title}</h1><p>{t.intro}</p></section><div className="docs-grid"><article className="panel"><h2>{t.usage}</h2><p>{t.body}</p><pre><code>{`curl -H "X-API-Key: bst_live_..." \\\n  http://localhost:8000/api/dna-protein?sequence=ATGGCC`}</code></pre><h3>{t.request}</h3><p>{t.guide}</p><a className="primary-button" href="mailto:api@bioapps.org">api@bioapps.org</a></article><article className="panel"><h2>{t.limits}</h2><p>{t.limitBody}</p><h3>{t.swagger}</h3><a className="primary-button" href="/docs">Open Swagger UI</a></article></div></main>;
}
